"use client";

import { useActionState } from "react";
import { importPhotosOnly } from "./actions";

export function ImportPhotosForm() {
  const [report, formAction, isPending] = useActionState(importPhotosOnly, null);
  return <details className="mt-6 border border-[color:var(--ink)]/20 bg-[color:var(--white)]"><summary className="cursor-pointer list-none px-4 py-4 text-sm font-medium transition hover:text-[color:var(--accent)]">Загрузить фото (ZIP)</summary><div className="border-t border-[color:var(--ink)]/12 px-4 py-5"><p className="max-w-3xl text-sm leading-6 text-[color:var(--ink)]/65">Для уже созданных товаров. Назовите главное фото <span className="font-mono-price">SKU.jpg</span>, дополнительные — <span className="font-mono-price">SKU-2.jpg</span>, <span className="font-mono-price">SKU-3.webp</span>. Папки внутри архива допустимы.</p><form action={formAction} className="mt-4 flex flex-wrap items-end gap-3"><label className="grid gap-2 text-sm font-medium">ZIP с фото <span className="font-normal text-[color:var(--ink)]/55">(до 200 МБ)</span><input required name="imagesZip" type="file" accept=".zip,application/zip,application/x-zip-compressed" className="max-w-full text-sm font-normal" /></label><button type="submit" disabled={isPending} className="min-h-11 bg-[color:var(--ink)] px-4 text-sm font-medium text-[color:var(--white)] transition hover:bg-[color:var(--accent)] disabled:cursor-wait disabled:opacity-60">{isPending ? "Загружаем…" : "Загрузить фото"}</button></form>{report ? <div className="mt-5 border-t border-[color:var(--ink)]/12 pt-4 text-sm">{report.updatedSkus.length ? <p><b>Фото обновлено для:</b> <span className="font-mono-price">{report.updatedSkus.join(", ")}</span></p> : null}{report.photosNotFound.length ? <p className="mt-3"><b>Фото не найдено для:</b> <span className="font-mono-price text-[color:var(--accent)]">{report.photosNotFound.join(", ")}</span></p> : null}{report.errors.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-[color:var(--accent)]">{report.errors.map((error) => <li key={error}>{error}</li>)}</ul> : null}</div> : null}</div></details>;
}
