"use client";

import Image from "next/image";
import Link from "next/link";
import { useCart } from "@/context/cart-context";

const formatPrice = new Intl.NumberFormat("ru-KZ");

export function CartItemsList({ className = "" }: { className?: string }) {
  const { items, incrementItem, decrementItem, removeItemEntirely } = useCart();

  return <ul className={`divide-y divide-[color:var(--ink)]/15 ${className}`}>{items.map((item) => <li key={`${item.id}-${item.size}`} className="cart-item-row py-5 sm:py-6"><div className="flex gap-3 sm:gap-5"><Link href={`/catalog/${item.id}`} aria-label={`Открыть товар: ${item.name}`} className="relative size-16 shrink-0 overflow-hidden border border-[color:var(--border)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--accent)] sm:size-24">{item.imageUrl ? <Image src={item.imageUrl} alt="" fill sizes="96px" className="object-cover" /> : <div className="size-full" style={{ backgroundColor: item.imageColor }} />}</Link><div className="min-w-0 flex-1"><p className="font-mono-price text-[0.65rem] tracking-[0.12em] text-[color:var(--accent)]">{item.brand.toUpperCase()}</p><Link href={`/catalog/${item.id}`} className="mt-1 block line-clamp-2 font-display text-xl leading-[0.95] hover:text-[color:var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--accent)] sm:text-2xl">{item.name}</Link><p className="mt-2 text-sm text-[color:var(--ink)]/60">Размер: {item.size}</p><p className="font-mono-price mt-3 text-sm">{formatPrice.format(item.price * item.quantity)} ₸</p></div><div className="flex shrink-0 flex-col items-end gap-2"><div className="flex min-h-11 items-center border border-[color:var(--border)]" aria-label={`Количество: ${item.quantity}`}><button type="button" onClick={() => decrementItem(item.id, item.size)} className="grid size-10 place-items-center text-lg text-[color:var(--ink)]/70 hover:bg-[color:var(--ink)]/5 hover:text-[color:var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--accent)]" aria-label="Уменьшить количество">−</button><span className="grid min-w-8 place-items-center px-1 font-mono-price text-sm">{item.quantity}</span><button type="button" onClick={() => incrementItem(item.id, item.size)} className="grid size-10 place-items-center text-lg text-[color:var(--ink)]/70 hover:bg-[color:var(--ink)]/5 hover:text-[color:var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--accent)]" aria-label="Увеличить количество">+</button></div><button type="button" onClick={() => removeItemEntirely(item.id, item.size)} className="min-h-11 px-2 text-sm text-[color:var(--ink)]/60 underline underline-offset-4 hover:text-[color:var(--accent)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--accent)]">Удалить</button></div></div></li>)}</ul>;
}
