import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { deleteHomeSection, toggleHomeSection } from "./actions";

const typeLabels: Record<string, string> = { newest: "Новинки", sale: "Со скидкой", category: "Категория", bestseller: "Бестселлеры", manual: "Вручную" };

export default async function HomeSectionsPage() {
  const sections = await prisma.homeSection.findMany({ orderBy: { position: "asc" } });
  return <main className="mx-auto max-w-[90rem] px-4 py-10 sm:px-6 sm:py-16 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5 border-b border-[color:var(--ink)]/15 pb-7"><div><p className="font-mono-price text-xs tracking-[0.16em] text-[color:var(--accent)]">ГЛАВНАЯ СТРАНИЦА</p><h1 className="font-display mt-3 text-5xl leading-none tracking-[-0.04em] sm:text-7xl">Разделы</h1></div><Link href="/admin/home-sections/new" className="flex min-h-11 items-center bg-[color:var(--ink)] px-4 text-sm font-medium text-[color:var(--white)] hover:bg-[color:var(--accent)]">Новый раздел</Link></div><div className="mt-8 overflow-x-auto border-y border-[color:var(--ink)]/15"><table className="w-full min-w-[680px] text-left text-sm"><thead className="font-mono-price text-[10px] tracking-[0.1em] text-[color:var(--ink)]/60"><tr><th className="px-4 py-4 font-normal">ПОЗИЦИЯ</th><th className="px-4 py-4 font-normal">НАЗВАНИЕ</th><th className="px-4 py-4 font-normal">ИСТОЧНИК</th><th className="px-4 py-4 font-normal">СТАТУС</th><th className="px-4 py-4 font-normal" /></tr></thead><tbody>{sections.map((section) => <tr key={section.id} className="border-t border-[color:var(--ink)]/10 hover:bg-[color:var(--white)]"><td className="px-4 py-4 font-mono-price">{section.position}</td><td className="px-4 py-4 font-medium">{section.title}</td><td className="px-4 py-4 text-[color:var(--ink)]/65">{typeLabels[section.type] ?? section.type}{section.categoryValue ? `: ${section.categoryValue}` : ""}</td><td className="px-4 py-4"><form action={toggleHomeSection.bind(null, section.id, !section.isActive)}><button className={`rounded-full px-3 py-1 font-mono-price text-[10px] ${section.isActive ? "bg-[color:var(--ink)] text-[color:var(--paper)]" : "bg-[color:var(--ink)]/10 text-[color:var(--ink)]/60"}`}>{section.isActive ? "ВКЛ" : "ВЫКЛ"}</button></form></td><td className="px-4 py-4"><div className="flex gap-4"><Link href={`/admin/home-sections/${section.id}`} className="underline decoration-[color:var(--gold)] underline-offset-4 hover:text-[color:var(--accent)]">Редактировать</Link><form action={deleteHomeSection.bind(null, section.id)}><button className="text-[color:var(--accent)] underline underline-offset-4">Удалить</button></form></div></td></tr>)}</tbody></table></div></main>;
}
